### ISSUE TITLE
Issue with optipng-bin

### ISSUE THREAD

**Issue by Jesterovskiy** [imagemin/imagemin-optipng#17]
I have issue in Travis build:

Error: spawn /app/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
The command '/bin/sh -c gulp' returned a non-zero code: 1

I'm not sure, if it helps, but can you make release with latest changes, where `optipng-bin` has version 4.0.0. Thank you

**Comment by Jesterovskiy** [comment]
@kevva @shinnn @sindresorhus ^^

**Comment by ianks** [comment]
Experiencing the same issue.

**Comment by smorcuend** [comment]
+1

**Comment by ianks** [comment]
This is a major issue breaking our builds.

**Comment by naseem-qadium** [comment]
+1 to major issue breaking builds

**Comment by swashcap** [comment]
Looking in to this problem. Here's what I see:

1. imagemin-optipng depends on [optipng-bin](https://github.com/imagemin/optipng-bin)
2. optipng-bin has a [postinstall script](https://github.com/imagemin/optipng-bin/blob/master/package.json#L30) which [attempts to `run` the package](https://github.com/imagemin/optipng-bin/blob/master/lib/install.js#L6)
3. This `run` likely fails on CI as there’s no optipng binary. The install script then attempts to [download the correct binary from sourceforge.net](https://github.com/imagemin/optipng-bin/blob/master/lib/install.js#L13)
4. The binary download definitely fails (our CI boxes don't have web access)
5. The download script [appears to log an error](https://github.com/imagemin/optipng-bin/blob/master/lib/install.js#L18), but this is either a silent log or a noop. This doesn't exit with a `>0` code as it should.
6. When attempting to `spawn` with [`optipng-bin`’s path](https://github.com/imagemin/optipng-bin/blob/master/index.js#L2) `spawn` fails with a `ENOENT` because there's no binary at that path: it never was download.

**Comment by swashcap** [comment]
Shoot, the bad download could also come from [this download method](https://github.com/kevva/bin-wrapper/blob/master/index.js#L196-L223). Rough stack trace:

1. Install script calls [`BinWrapper#run`](https://github.com/kevva/bin-wrapper/blob/12a68d1ad3e3841049deed724d6535a4660b4005/index.js#L123)
2. which calls [`BinWrapper#findExisting`](https://github.com/kevva/bin-wrapper/blob/12a68d1ad3e3841049deed724d6535a4660b4005/index.js#L180)
3. `BinWrapper#findExisting` [stats for the _vendor_ directory](https://github.com/kevva/bin-wrapper/blob/12a68d1ad3e3841049deed724d6535a4660b4005/index.js#L181), which fails
4. which calls [`BinWrapper#download`](https://github.com/kevva/bin-wrapper/blob/12a68d1ad3e3841049deed724d6535a4660b4005/index.js#L203), which triggers a [download](https://www.npmjs.com/package/download) based on the OS/architecture

This process could fail, too.

**Comment by SerdarSanri** [comment]
Appearently opti-png bin file is infected with ML/PE-A malware. If you have an antimalware or similar tool, it will detect and remove the file. At least that's the case on my end that fails to install from npm

**Comment by Alexandre-Passerelle** [comment]
**npm rebuild** solved the problem for me.
