### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by armpogart** [imagemin/imagemin-optipng#18]
We are using `gulp-imagemin` but this issue is related exactly to jpegtran. We have a build system running in docker container and base on `node:alpine`, recently it started to fail. The minimal case to replicate the problem.

1. `docker run -it node:alpine /bin/sh`
Install some build dependencies
2. `apk add --update --no-cache make g++ automake autoconf libtool nasm libpng-dev`
3. `npm install optipng-bin`

We get following output that is worth mentioning
````shell
> optipng-bin@4.0.0 postinstall /node_modules/optipng-bin
> node lib/install.js

  ⚠ spawn /node_modules/optipng-bin/vendor/optipng ENOENT
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/node_modules/optipng-bin/vendor" --bindir="/node_modules/optipng-bin/vendor" && make install
Command failed: ./configure --with-system-zlib --prefix="/node_modules/optipng-bin/vendor" --bindir="/node_modules/optipng-bin/vendor"
/bin/sh: ./configure: not found

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
````

Previously it was running ok on the same build system. I can't say exactly when it first started to fail as I was using cache and I have noticed the problem after cleaning the cache.

**Comment by armpogart** [comment]
Maybe related to https://github.com/imagemin/jpegtran-bin/issues/83

**Comment by naseem-qadium** [comment]
Likewise issues with this plugin using node-alpine docker image.

**Comment by naseem-qadium** [comment]
I believe this might have to do with Sourceforge being down.

**Comment by stevenscg** [comment]
@naseem-qadium @armpogart Were you able to resolve this issue? I am seeing it again in the last 48 hours, but not as recently as 3 days ago on the same build.

**Comment by stevenscg** [comment]
I am seeing this failure in an Alpine Linux 3.7 container.

node 8.9.3
npm 5.5.1

**Comment by accnops** [comment]
I'm also seeing this. Latest node:alpine image.

**Comment by stevenscg** [comment]
@accnops Was it working for you previously and recently started failing?

**Comment by accnops** [comment]
@stevenscg, that's exactly what I'm experiencing. Nothing changed, and now it fails.

**Comment by sebastian-schlecht** [comment]
Same here on node:8-alpine

**Comment by bericp1** [comment]
We're seeing the same issue today. It appears the binary isn't building correctly for alpine during `yarn`/`npm install`/`npm rebuild` even though other packages with native binaries are building correctly. Version didn't change at all (locked with `yarn.lock`) and nor did the alpine docker image we're using. Check out this possibly relevant discussion [here on the Unix stackexchange](https://unix.stackexchange.com/questions/18061/why-does-sh-say-not-found-when-its-definitely-there).

![screenshot of terminal](https://d.pr/i/aDTPbZ.png)

**Comment by bericp1** [comment]
This is definitely because of the SourceForge outage :/

![terminal screenshot](https://d.pr/i/g711XX.png)

I'd recomend thumbsuping imagemin/optipng-bin#94 so that this is at least more apparent when it occurs.

**Comment by dylansmith** [comment]
I opened a PR to resolve this: https://github.com/imagemin/optipng-bin/pull/95, please give it a 👍!

**Comment by stevenscg** [comment]
Thanks @bericp1 and @dylansmith! I added thumbsup and subscribed to both of those. Pretty nasty failure mode.

**Comment by armpogart** [comment]
@stevenscg yep, same issue now, it was resolved before that. I think it was just SourceForge problem as it resolved by itself a couple of days later. And now again my build are failing.

**Comment by brabeji** [comment]
IMHO this is a `bin-build` issue: https://github.com/imagemin/optipng-bin/issues/84#issuecomment-370106320

**Comment by gjovanov** [comment]
Any other alternative to download it for alpine precompiled?
