### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by davetgreen** [imagemin/imagemin-optipng#3]
I'm getting this when I install on a Windows 7 32 bit machine:

> node lib/install.js

  ‼ spawn ENOENT
  ‼ optipng pre-build test failed
  i compiling from source
  × Error: Command failed: '.' is not recognized as an internal or external
and,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
imagemin-optipng@4.0.0 node_modules\imagemin-optipng
├── is-png@1.0.0
├── exec-buffer@1.1.2 (rimraf@2.2.8, tempfile@1.1.0)
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
└── optipng-bin@2.0.4 (logalot@2.1.0, bin-build@2.1.0, bin-wrapper@2.1.3)

Cheers,
Dave

**Comment by kevva** [comment]
Building is not supported on Windows platforms.
